# Generated by Django 5.2.5 on 2025-08-19 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('client_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('payload_size_bytes', models.IntegerField(blank=True, null=True)),
                ('session_key_hash', models.CharField(blank=True, help_text='SHA256 of session key (for audit only)', max_length=128, null=True)),
                ('client_signature_verified', models.BooleanField(default=False)),
                ('middleware_signature', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_size_bytes', models.IntegerField(blank=True, null=True)),
                ('downstream_response_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_step', models.CharField(blank=True, max_length=128, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('actor', models.CharField(default='middleware', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('record_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['transaction_id', 'timestamp'],
                'indexes': [models.Index(fields=['transaction_id', '-timestamp'], name='api_auditlo_transac_218096_idx')],
            },
        ),
        migrations.CreateModel(
            name='MiddlewareKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, default='active', max_length=64)),
                ('private_key_pem', models.TextField(help_text='PEM encoded private key (encrypted at rest recommended)')),
                ('public_key_pem', models.TextField(help_text='PEM encoded public key')),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['label', 'active'], name='api_middlew_label_1de0fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('new_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_key_logs', to='api.middlewarekey')),
                ('old_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_key_logs', to='api.middlewarekey')),
            ],
            options={
                'ordering': ['-rotated_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.CharField(db_index=True, max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nonce'], name='api_usednon_nonce_4cf0cf_idx')],
            },
        ),
    ]
