# Generated by Django 5.2.5 on 2025-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='banking_route',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
