# Generated by Django 5.2.5 on 2025-08-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_auditlog_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.CharField(default='middleware'),
        ),
    ]
