# Generated by Django 5.2.4 on 2025-07-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usednonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlewarekey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
