# Generated by Django 5.2.5 on 2025-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_middlewarekey_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usednonce',
            index=models.Index(fields=['timestamp'], name='api_usednon_timesta_d2be30_idx'),
        ),
        migrations.AlterModelTable(
            name='usednonce',
            table='api_usednonce',
        ),
    ]
