# Generated by Django 5.2.5 on 2025-08-21 14:55

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auditlog_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmetadata',
            name='decryption_time_ms',
            field=models.FloatField(blank=True, help_text='Decryption time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='encryption_time_ms',
            field=models.FloatField(blank=True, help_text='Encryption time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='middlewarekey',
            name='private_key_pem',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Private Key'),
        ),
    ]
