# Generated by Django 5.2.5 on 2025-08-10 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usednonce_api_usednon_timesta_d2be30_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.FloatField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('client_ip', models.GenericIPAddressField(help_text='Client IP address')),
                ('client_public_key_hash', models.CharField(help_text='SHA256 hash of client public key', max_length=64)),
                ('nonce', models.CharField(db_index=True, max_length=255)),
                ('target_url', models.CharField(help_text='Target downstream URL', max_length=500)),
                ('payload_hash', models.CharField(help_text='SHA256 hash of transaction payload', max_length=64)),
                ('payload_size_bytes', models.IntegerField(default=0, help_text='Size of encrypted payload in bytes')),
                ('session_key_hash', models.CharField(help_text='SHA256 hash of session key', max_length=64)),
                ('middleware_signature', models.TextField(help_text='Middleware signature for this transaction')),
                ('client_signature_verified', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned')),
                ('downstream_response_time_ms', models.FloatField(blank=True, help_text='Downstream API response time', null=True)),
                ('response_size_bytes', models.IntegerField(default=0, help_text='Size of response in bytes')),
                ('error_message', models.TextField(blank=True, help_text='Error message if transaction failed', null=True)),
                ('error_step', models.CharField(blank=True, help_text='Step where error occurred', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_transaction_metadata',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_transac_timesta_e8b28d_idx'), models.Index(fields=['client_ip'], name='api_transac_client__315c2e_idx'), models.Index(fields=['nonce'], name='api_transac_nonce_f356cd_idx'), models.Index(fields=['status_code'], name='api_transac_status__8bff33_idx'), models.Index(fields=['target_url'], name='api_transac_target__e02019_idx')],
            },
        ),
    ]
