# Generated by Django 5.2.5 on 2025-08-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transactionmetadata_decryption_time_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='details',
        ),
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='error_step',
        ),
    ]
