version: '3.8'
services:
  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    env_file:
      - ./middleware/.env
    volumes:
      - staticfiles_middleware:/app/staticfiles
    ports:
      - "8001:8001"
    depends_on:
      - server
    command: gunicorn securecipher.wsgi:application --bind 0.0.0.0:8001 --workers 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - staticfiles_server:/app/staticfiles
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - middleware
      - server

volumes:
  staticfiles_middleware:
  staticfiles_server:
