# Exported from Render on 2025-08-12T21:56:43Z
services:
- type: web
  name: securecipher_middleware
  runtime: python
  repo: https://github.com/King-Austin/securecipher_project
  plan: free
  region: oregon
  buildCommand: bash setup.sh
  startCommand: gunicorn securecipher.wsgi:application --workers 3 --bind 0.0.0.0:$PORT
  autoDeployTrigger: commit
  rootDir: ./middleware
- type: web
  name: securecipher_server
  runtime: python
  repo: https://github.com/King-Austin/securecipher_project
  plan: free
  envVars:
  - key: DEBUG
    sync: false
  - key: FIELD_ENCRYPTION_KEY
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: bash setup.sh
  startCommand: gunicorn bankingapi.wsgi:application --workers 3
  autoDeployTrigger: commit
  rootDir: ./server
- type: web
  name: Securecipherbank
  runtime: static
  repo: https://github.com/King-Austin/securecipher_project
  buildCommand: npm install; npm run build
  staticPublishPath: dist
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  autoDeployTrigger: commit
  rootDir: ./frontend
version: "1"
databases:
- name: securecipher_db
  user: securecipher_user
  password: securecipher_password
  host: securecipher_db_host
  port: 5432
  dbname: securecipher_db