# Generated by Django 5.2.5 on 2025-08-17 00:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bvn_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_hash',
        ),
        migrations.AlterField(
            model_name='apikeypair',
            name='private_key',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Private Key'),
        ),
    ]
